[project]
name = "nicerpdb"
version = "0.1.1"
description = "A TUI frontend for pdb"
requires-python = ">=3.9"
readme = "README.md"
dependencies = ["rich", "click"]

[project.scripts]
nicerpdb = "nicerpdb.cli:nicerpdb"
